import '../model/currency_list.dart';

const List<CurrencyList> currencyList = [
  CurrencyCrypto('BTC', 'Bitcoin', 'BTC'),
  Category('A'),
  Currency('AUD', 'Australian Dollar', '\$'),
  Category('B'),
  Currency('BRL', 'Brazilian Real', 'R\$'),
  Currency('GBP', 'British Pound Sterling', '£'),
  Currency('BGN', 'Bulgarian Lev', 'лв'),
  Category('C'),
  Currency('CAD', 'Canadian Dollar', '\$'),
  Currency('CNY', 'Chinese Yuan', '¥'),
  Currency('HRK', 'Croatian Kuna', 'kn'),
  Currency('CZK', 'Czech Koruna', 'Kč'),
  Category('D'),
  Currency('DKK', 'Danish Krone', 'kr'),
  Category('E'),
  Currency('EUR', 'Euro', '€'),
  // Category('F'),
  // Category('G'),
  Category('H'),
  Currency('HKD', 'Hong Kong Dollar', '\$'),
  Currency('HUF', 'Hungarian Forint', 'Ft'),
  Category('I'),
  Currency('ISK', 'Icelandic Króna', 'kr'),
  Currency('INR', 'Indian Rupee', '₹'),
  Currency('IDR', 'Indonesian Rupiah', 'Rp'),
  Currency('ILS', 'Israeli New Sheqel', '₪'),
  Category('J'),
  Currency('JPY', 'Japanese Yen', '¥'),
  // Category('K'),
  // Category('L'),
  Category('M'),
  Currency('MYR', 'Malaysian Ringgit', 'RM'),
  Currency('MXN', 'Mexican Peso', '\$'),
  // Category('O'),
  Category('N'),
  Currency('NOK', 'Norwegian Krone', 'kr'),
  Currency('NZD', 'New Zealand Dollar', '\$'),
  Category('P'),
  Currency('PHP', 'Philippine Peso', '₱'),
  Currency('PLN', 'Polish Zloty', 'zł'),
  // Category('Q'),
  Category('R'),
  Currency('RON', 'Romanian Leu', 'lei'),
  Currency('RUB', 'Russian Ruble', 'руб'),
  Category('S'),
  Currency('SGD', 'Singapore Dollar', '\$'),
  Currency('ZAR', 'South African Rand', 'R'),
  Currency('KRW', 'South Korean Won', '₩'),
  Currency('SEK', 'Swedish Krona', 'kr'),
  Currency('CHF', 'Swiss Franc', 'Fr.'),
  Category('T'),
  Currency('THB', 'Thai Baht', '฿'),
  Currency('TRY', 'Turkish New Lira', ''),
  Category('U'),
  Currency('USD', 'United States Dollar', '\$'),
  // Category('V'),
  // Category('W'),
  // Category('X'),
  // Category('Y'),
  // Category('Z'),
];
