import '../model/currency_list.dart';

const List<CurrencyList> currencyList = [
  Currency('BTC', 'Bitcoin', 'BTC', true),
  Category('A'),
  Currency('AUD', 'Australian Dollar', '\$', false),
  Category('B'),
  Currency('BRL', 'Brazilian Real', 'R\$', false),
  Currency('GBP', 'British Pound Sterling', '£', false),
  Currency('BGN', 'Bulgarian Lev', 'лв', false),
  Category('C'),
  Currency('CAD', 'Canadian Dollar', '\$', false),
  Currency('CNY', 'Chinese Yuan', '¥', false),
  Currency('HRK', 'Croatian Kuna', 'kn', false),
  Currency('CZK', 'Czech Koruna', 'Kč', false),
  Category('D'),
  Currency('DKK', 'Danish Krone', 'kr', false),
  Category('E'),
  Currency('EUR', 'Euro', '€', false),
  // Category('F'),
  // Category('G'),
  Category('H'),
  Currency('HKD', 'Hong Kong Dollar', '\$', false),
  Currency('HUF', 'Hungarian Forint', 'Ft', false),
  Category('I'),
  Currency('ISK', 'Icelandic Króna', 'kr', false),
  Currency('INR', 'Indian Rupee', '₹', false),
  Currency('IDR', 'Indonesian Rupiah', 'Rp', false),
  Currency('ILS', 'Israeli New Sheqel', '₪', false),
  Category('J'),
  Currency('JPY', 'Japanese Yen', '¥', false),
  // Category('K'),
  // Category('L'),
  Category('M'),
  Currency('MYR', 'Malaysian Ringgit', 'RM', false),
  Currency('MXN', 'Mexican Peso', '\$', false),
  // Category('O'),
  Category('N'),
  Currency('NOK', 'Norwegian Krone', 'kr', false),
  Currency('NZD', 'New Zealand Dollar', '\$', false),
  Category('P'),
  Currency('PHP', 'Philippine Peso', '₱', false),
  Currency('PLN', 'Polish Zloty', 'zł', false),
  // Category('Q'),
  Category('R'),
  Currency('RON', 'Romanian Leu', 'lei', false),
  Currency('RUB', 'Russian Ruble', 'руб', false),
  Category('S'),
  Currency('SGD', 'Singapore Dollar', '\$', false),
  Currency('ZAR', 'South African Rand', 'R', false),
  Currency('KRW', 'South Korean Won', '₩', false),
  Currency('SEK', 'Swedish Krona', 'kr', false),
  Currency('CHF', 'Swiss Franc', 'Fr.', false),
  Category('T'),
  Currency('THB', 'Thai Baht', '฿', false),
  Currency('TRY', 'Turkish New Lira', '', false),
  Category('U'),
  Currency('USD', 'United States Dollar', '\$', false),
  // Category('V'),
  // Category('W'),
  // Category('X'),
  // Category('Y'),
  // Category('Z'),
];
