import '../model/currency_list.dart';

const List<CurrencyList> currencyList = [
  Currency('BTC', 'Bitcoin', 'BTC', false),
  Category('A'),
  Currency('AUD', 'Australian Dollar', '\$', true),
  Category('B'),
  Currency('BRL', 'Brazilian Real', 'R\$', true),
  Currency('GBP', 'British Pound Sterling', '£', true),
  Currency('BGN', 'Bulgarian Lev', 'лв', true),
  Category('C'),
  Currency('CAD', 'Canadian Dollar', '\$', true),
  Currency('CNY', 'Chinese Yuan', '¥', true),
  Currency('HRK', 'Croatian Kuna', 'kn', true),
  Currency('CZK', 'Czech Koruna', 'Kč', true),
  Category('D'),
  Currency('DKK', 'Danish Krone', 'kr', true),
  Category('E'),
  Currency('EUR', 'Euro', '€', true),
  // Category('F'),
  // Category('G'),
  Category('H'),
  Currency('HKD', 'Hong Kong Dollar', '\$', true),
  Currency('HUF', 'Hungarian Forint', 'Ft', true),
  Category('I'),
  Currency('ISK', 'Icelandic Króna', 'kr', true),
  Currency('INR', 'Indian Rupee', '₹', true),
  Currency('IDR', 'Indonesian Rupiah', 'Rp', true),
  Currency('ILS', 'Israeli New Sheqel', '₪', true),
  Category('J'),
  Currency('JPY', 'Japanese Yen', '¥', true),
  // Category('K'),
  // Category('L'),
  Category('M'),
  Currency('MYR', 'Malaysian Ringgit', 'RM', true),
  Currency('MXN', 'Mexican Peso', '\$', true),
  // Category('O'),
  Category('N'),
  Currency('NOK', 'Norwegian Krone', 'kr', true),
  Currency('NZD', 'New Zealand Dollar', '\$', true),
  Category('P'),
  Currency('PHP', 'Philippine Peso', '₱', true),
  Currency('PLN', 'Polish Zloty', 'zł', true),
  // Category('Q'),
  Category('R'),
  Currency('RON', 'Romanian Leu', 'lei', true),
  Currency('RUB', 'Russian Ruble', 'руб', true),
  Category('S'),
  Currency('SGD', 'Singapore Dollar', '\$', true),
  Currency('ZAR', 'South African Rand', 'R', true),
  Currency('KRW', 'South Korean Won', '₩', true),
  Currency('SEK', 'Swedish Krona', 'kr', true),
  Currency('CHF', 'Swiss Franc', 'Fr.', true),
  Category('T'),
  Currency('THB', 'Thai Baht', '฿', true),
  Currency('TRY', 'Turkish New Lira', '', true),
  Category('U'),
  Currency('USD', 'United States Dollar', '\$', true),
  // Category('V'),
  // Category('W'),
  // Category('X'),
  // Category('Y'),
  // Category('Z'),
];
